name: Anleitungen zu PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'anleitungen/**.md'
      - '.github/release.yaml'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: anleitungen
          output_dir: pdfs
          images_dir: anleitungen
          image_import: ./images
          build_html: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: docs/**
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true 